### ISSUE TITLE
password reset does not work with non-oauth email

### ISSUE THREAD

**Issue by Ocawesome101** [Ale32bit/DevBin#45]
A while ago I registered an account with an email we'll call `abc@gmail.com`.  I forgot about it for a while until I tried to sign into it today and the credentials weren't working.  I tried to reset the password for it, but putting `abc@gmail.com` into the Email box returns `An error occurred while processing your request.`

**Comment by Ale32bit** [comment]
53d651b2f2788dd530bc452c3130ddbe6bdc7756 should fix this issue automatically in the future.
